<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:atl="http://www.eclipse.org/gmt/2005/ATL" xmlns:ocl="http://www.eclipse.org/gmt/2005/OCL">
  <atl:Module name="exam2mvc">
    <inModels location="2:32-2:44" name="IN" metamodel="/3"/>
    <outModels location="2:8-2:26" name="OUT" metamodel="/4"/>
    <elements xsi:type="atl:MatchedRule" location="4:1-11:2" name="Exams">
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="mvc">
          <type xsi:type="ocl:OclModelElement" location="8:10-8:27" name="Exam" model="/4"/>
          <bindings location="9:5-9:30" propertyName="examItems">
            <value xsi:type="ocl:NavigationOrAttributeCallExp" location="9:18-9:30"
                name="elements">
              <source xsi:type="ocl:VariableExp" location="9:18-9:21" referredVariable="/0/@elements.0/@inPattern/@elements.0"/>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern location="5:3-6:22">
        <elements xsi:type="atl:SimpleInPatternElement" location="6:4-6:22" varName="xml"
            variableExp="/0/@elements.0/@outPattern/@elements.0/@bindings.0/@value/@source">
          <type xsi:type="ocl:OclModelElement" location="6:10-6:22" name="Exam" model="/3"/>
        </elements>
      </inPattern>
    </elements>
    <elements xsi:type="atl:MatchedRule" location="13:1-27:2" name="OpenQuestion">
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="controller" variableExp="/1/@bindings.0/@value">
          <type xsi:type="ocl:OclModelElement" location="17:16-17:43" name="OpenController"
              model="/4"/>
        </elements>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="model">
          <type xsi:type="ocl:OclModelElement" location="23:11-23:28" name="Open"
              model="/4"/>
          <bindings location="24:9-24:33" propertyName="question">
            <value xsi:type="ocl:NavigationOrAttributeCallExp" location="24:21-24:33"
                name="question">
              <source xsi:type="ocl:VariableExp" location="24:21-24:24" referredVariable="/0/@elements.1/@inPattern/@elements.0"/>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern location="14:5-15:28">
        <elements xsi:type="atl:SimpleInPatternElement" location="15:3-15:28" varName="xml"
            variableExp="/0/@elements.1/@outPattern/@elements.1/@bindings.0/@value/@source">
          <type xsi:type="ocl:OclModelElement" location="15:9-15:28" name="OpenElement"
              model="/3"/>
        </elements>
      </inPattern>
    </elements>
    <elements xsi:type="atl:MatchedRule" location="29:1-43:2" name="MultipleChoice">
      <outPattern>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="controller" variableExp="/2/@bindings.0/@value">
          <type xsi:type="ocl:OclModelElement" location="33:16-33:53" name="MultipleChoiceController"
              model="/4"/>
        </elements>
        <elements xsi:type="atl:SimpleOutPatternElement" varName="model">
          <type xsi:type="ocl:OclModelElement" location="39:11-39:38" name="MultipleChoice"
              model="/4"/>
          <bindings location="40:9-40:33" propertyName="question">
            <value xsi:type="ocl:NavigationOrAttributeCallExp" location="40:21-40:33"
                name="question">
              <source xsi:type="ocl:VariableExp" location="40:21-40:24" referredVariable="/0/@elements.2/@inPattern/@elements.0"/>
            </value>
          </bindings>
        </elements>
      </outPattern>
      <inPattern location="30:5-31:38">
        <elements xsi:type="atl:SimpleInPatternElement" location="31:3-31:38" varName="xml"
            variableExp="/0/@elements.2/@outPattern/@elements.1/@bindings.0/@value/@source">
          <type xsi:type="ocl:OclModelElement" location="31:9-31:38" name="MultipleChoiceElement"
              model="/3"/>
        </elements>
      </inPattern>
    </elements>
  </atl:Module>
  <atl:SimpleOutPatternElement varName="view">
    <type xsi:type="ocl:OclModelElement" location="18:10-18:31" name="OpenView" model="/4"/>
    <bindings location="19:3-19:27" propertyName="controller">
      <value xsi:type="ocl:VariableExp" location="19:17-19:27" referredVariable="/0/@elements.1/@outPattern/@elements.0"/>
    </bindings>
    <bindings location="20:3-20:22" propertyName="fontName">
      <value xsi:type="ocl:StringExp" location="20:15-20:22" stringSymbol="Times"/>
    </bindings>
    <bindings location="21:3-21:21" propertyName="fontColor">
      <value xsi:type="ocl:StringExp" location="21:16-21:21" stringSymbol="Red"/>
    </bindings>
  </atl:SimpleOutPatternElement>
  <atl:SimpleOutPatternElement varName="view">
    <type xsi:type="ocl:OclModelElement" location="34:10-34:41" name="MultipleChoiceView"
        model="/4"/>
    <bindings location="35:3-35:27" propertyName="controller">
      <value xsi:type="ocl:VariableExp" location="35:17-35:27" referredVariable="/0/@elements.2/@outPattern/@elements.0"/>
    </bindings>
    <bindings location="36:3-36:22" propertyName="fontName">
      <value xsi:type="ocl:StringExp" location="36:15-36:22" stringSymbol="Times"/>
    </bindings>
    <bindings location="37:3-37:21" propertyName="fontColor">
      <value xsi:type="ocl:StringExp" location="37:16-37:21" stringSymbol="Red"/>
    </bindings>
  </atl:SimpleOutPatternElement>
  <ocl:OclModel location="2:37-2:44" name="ExamXML" elements="/0/@elements.0/@inPattern/@elements.0/@type /0/@elements.1/@inPattern/@elements.0/@type /0/@elements.2/@inPattern/@elements.0/@type"
      model="/0/@inModels.0"/>
  <ocl:OclModel location="2:14-2:26" name="AssistantMVC" elements="/0/@elements.0/@outPattern/@elements.0/@type /0/@elements.1/@outPattern/@elements.0/@type /1/@type /0/@elements.1/@outPattern/@elements.1/@type /0/@elements.2/@outPattern/@elements.0/@type /2/@type /0/@elements.2/@outPattern/@elements.1/@type"
      model="/0/@outModels.0"/>
</xmi:XMI>
