<?xml version="1.0" encoding="UTF-8"?>
<Difference:DiffModel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Difference="http://www.eclipse.org/Difference">
  <ownedElements xsi:type="Difference:RemoveModelElement">
  		<rightParent href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#/"/>
     	<leftElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol11.ecore#//ExamData"/>
  </ownedElements>
  <ownedElements xsi:type="Difference:AddModelElement">
  		<leftParent href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol11.ecore#//ExamItem"/>
     	<rightElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#//ExamItem/question"/>
  </ownedElements>
  <ownedElements xsi:type="Difference:AddModelElement">
  		<leftParent href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol11.ecore#//ExamItem"/>
     	<rightElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#//ExamItem/value"/>
  </ownedElements>
</Difference:DiffModel>
