<?xml version="1.0" encoding="UTF-8"?>
<Difference:DiffModel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:Difference="http://www.eclipse.org/Difference">
  <ownedElements xsi:type="Difference:ModelElementChangeLeftTarget">
  		<rightParent href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#/"/>
     	<leftElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol8.ecore#//Observable"/>
  </ownedElements>
  <ownedElements xsi:type="Difference:ModelElementChangeRightTarget">
  		<leftParent href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol8.ecore#//ExamItem"/>
     	<rightElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#//ExamItem/question"/>
  </ownedElements>
  <ownedElements xsi:type="Difference:ReferenceChangeLeftTarget">
  		<reference href="http://www.eclipse.org/emf/2002/Ecore#//EClass/eSuperTypes"/>
         <rightElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#//Exam"/>
          <leftElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol8.ecore#//Exam"/>
          <leftTarget href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol8.ecore#//Observable"/>
  </ownedElements>
  <ownedElements xsi:type="Difference:ReferenceChangeLeftTarget">
  		<reference href="http://www.eclipse.org/emf/2002/Ecore#//EClass/eSuperTypes"/>
         <rightElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol9.ecore#//ExamItem"/>
          <leftElement href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol8.ecore#//ExamItem"/>
          <leftTarget href="platform:/resource/examination-assistant/metamodels/AssistantMVCEvol8.ecore#//Observable"/>
 </ownedElements>
</Difference:DiffModel>
