<?xml version="1.0" encoding="UTF-8"?>
<exam:Evaluation xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exam="http://gts.inf.um.es/tests/ExamXML" question="pregunta">
  <exam>
    <elements xsi:type="exam:OpenElement" value="valor"/>
  </exam>
</exam:Evaluation>
